version: "3.8"

services:
  proxy:
    image: nginx:1.15.8-alpine
    container_name: nginx.cityvizor.cesko.digital
    ports:
      # Client
      - "4200:80"
      # Redesign
      - "4201:81"
      # Strapi server
      - "1337:1337"
    volumes:
      - ./nginx:/etc/nginx:ro
    environment:
      NGINX_HOST: cityvizor.cesko.digital
      NGINX_PORT: 80

  backend-kotlin:
    image: backend-kotlin
    build: server-kotlin/.
    container_name: backend.cityvizor.cesko.digital
    environment:
      JDBC_URL: jdbc:postgresql://db.cityvizor.cesko.digital:5432/cityvizor
    depends_on:
      - postgres
      - proxy

  cityvizor-server:
    image: cityvizor-server
    build: 
      context: ./server
      target: prod
    command: bash src/scripts/wait-for-it.sh -h db.cityvizor.cesko.digital -p 5432 -- node dist/server.js
    container_name: server.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on:
      - postgres
      - proxy

  cityvizor-worker:
    image: cityvizor-server
    build: 
      context: ./server
      target: prod
    command: bash src/scripts/wait-for-it.sh -h db.cityvizor.cesko.digital -p 5432 -- node dist/worker.js
    container_name: worker.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    volumes:
      - ./data:/user/src/app/data
    depends_on:
      - postgres
  cityvizor-client:
    image: cityvizor-client
    build:
      context: ./client
      target: prod
    container_name: client.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    depends_on:
      - proxy

  cityvizor-server-strapi:
    image: cityvizor-server-strapi
    build: ./redesign/server-strapi
    container_name: strapi.cityvizor.cesko.digital
    environment:
      NODE_ENV: production
      DATABASE_HOST: db.cityvizor.cesko.digital
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: pass
    depends_on:
      - proxy
  cityvizor-redesign-client:
    image: cityvizor-redesign-client
    build:
      context: ./redesign/client-redesign
    container_name: client-redesign.cityvizor.cesko.digital
    environment:
      NODE_ENV: local
    depends_on:
      - proxy

  postgres:
    image: postgres:11.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: db.cityvizor.cesko.digital
    environment:
      POSTGRES_DB: cityvizor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - ./database/demo_dump.sql:/docker-entrypoint-initdb.d/demo_dump.sql
    ports:
      - 5432:5432
